top_srcdir   = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24
top_builddir = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24
srcdir       = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/modules/proxy
builddir     = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/modules/proxy
VPATH        = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/modules/proxy
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
