top_srcdir   = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24
top_builddir = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24
srcdir       = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/server/mpm
builddir     = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/server/mpm
VPATH        = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
