top_srcdir   = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24
top_builddir = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24
srcdir       = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/modules/filters
builddir     = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/modules/filters
VPATH        = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/modules/filters

include $(top_srcdir)/build/special.mk

