top_srcdir   = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24
top_builddir = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24
srcdir       = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/modules/aaa
builddir     = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/modules/aaa
VPATH        = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/modules/aaa

include $(top_srcdir)/build/special.mk

