top_srcdir   = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24
top_builddir = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24
srcdir       = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/os
builddir     = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/os
VPATH        = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
