top_srcdir   = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24
top_builddir = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24
srcdir       = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/server/mpm/prefork
builddir     = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/server/mpm/prefork
VPATH        = /home/dcashman/thesis/misc/ASLR/httpd-2.2.24/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
